
let firstName: String = "Shruti"; 
let lastName: String = "Kumari"; 
let ageName: Number = 18; 
let addressName: String = "Pawapuri"; 
let stateName: String = "Bihar"; 
let fathersName: String = "Deepak kumar"; 
let mothersName: String = "Kumari Baby Gupta"; 

console.log(typeof firstName);
console.log(typeof lastName);
console.log(typeof ageName);
console.log(typeof addressName);
console.log(typeof stateName)
console.log(typeof fathersName);
console.log(typeof mothersName);
